# Generated by Django 3.2.7 on 2023-04-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_order_taxprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
